baseURL = '/blog'
languageCode = 'en-us'
title = 'Café Musain'
theme = 'hyde'

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[params]
  math = true
  author.name = "Ada Huang"
  author.email = "ada.zan.huang@gmail.com"
  myown_css = ["css/myown.css"]

[[module.mounts]]
  source = 'images'
  target = 'static/images'

[taxonomies]
  year = "year"
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  [[menu.nav]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 1

  [[menu.nav]]
  identifier = "year"
  name = "Years"
  url = "/year/"
  weight = 2
